name: first-workflow
on: [push]
jobs:
  check-python-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10.12 
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.12 
      - name: Check Version
        run: python --version
